### ISSUE TITLE
java.lang.RuntimeException: The dimensions from location and bearing drawables should be match

### ISSUE THREAD

**Issue by sergsel** [NAXAM/mapbox-xamarin-forms#14]
FATAL EXCEPTION: ControllerMessenger
Process: net.trip_hub.istambul, PID: 21708
java.lang.RuntimeException: The dimensions from location and bearing drawables should be match
	at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.setForegroundDrawables(MyLocationView.java:193)
	at com.mapbox.mapboxsdk.maps.widgets.MyLocationViewSettings.setForegroundDrawable(MyLocationViewSettings.java:189)
	at com.mapbox.mapboxsdk.maps.widgets.MyLocationViewSettings.initialise(MyLocationViewSettings.java:98)
	at com.mapbox.mapboxsdk.maps.MapboxMap.initialise(MapboxMap.java:99)
	at com.mapbox.mapboxsdk.maps.MapView.initialiseMap(MapView.java:220)
	at com.mapbox.mapboxsdk.maps.MapView.access$800(MapView.java:70)
	at com.mapbox.mapboxsdk.maps.MapView$6$1.run(MapView.java:326)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.support.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:148)
	at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:466)
	at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:420)
	at android.support.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:234)
	at android.support.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:140)
	at android.support.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:123)
	at android.support.test.espresso.action.Tap.sendSingleTap(Tap.java:170)
	at android.support.test.espresso.action.Tap.access$100(Tap.java:31)
	at android.support.test.espresso.action.Tap$1.sendTap(Tap.java:46)
	at android.support.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:136)
	at android.support.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:355)
	at android.support.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:242)
	at android.support.test.espresso.ViewInteraction.access$100(ViewInteraction.java:62)
	at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:149)
	at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:146)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7230)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by tuyen-vuduc** [comment]
How could you get to this error? Plz provide a sample code to replicate the issue.

**Comment by tuyen-vuduc** [comment]
@sergsel I am going to close this issue. If you still face the issue, plz re-open.
