### ISSUE TITLE
Java.IO.FileNotFoundException

### ISSUE THREAD

**Issue by mindport** [NAXAM/mapbox-xamarin-forms#75]
I sometimes get this weird error, the file its looking for is the title "Make Mapbox maps better.."

`
Info (7764) / MonoDroid: Java.Lang.RuntimeException: File Gör Mapbox kartor bättre from xml type layout resource ID #0x7f0b004f ---> Java.IO.FileNotFoundException: Gör Mapbox kartor bättre
Info (7764) / MonoDroid:    --- End of inner exception stack trace ---
Info (7764) / MonoDroid:   at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <1d2fdefea4314028a5260e7fd847966a>:0 
Info (7764) / MonoDroid:   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <1d2fdefea4314028a5260e7fd847966a>:0 
Info (7764) / MonoDroid:   at Android.Views.LayoutInflater.Inflate (System.Int32 resource, Android.Views.ViewGroup root) [0x00044] in <4032d0be3ee64d1a892a0f3849515de6>:0 
Info (7764) / MonoDroid:   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnCreate (Android.OS.Bundle savedInstanceState, Xamarin.Forms.Platform.Android.ActivationFlags flags) [0x00064] in <ad1547340995436c904507feabf68321>:0 
Info (7764) / MonoDroid:   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00000] in <ad1547340995436c904507feabf68321>:0 
Info (7764) / MonoDroid:   at Truckify.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x0007d] in <2df84fd60160497b83c7eeae6f18900e>:0 
Info (7764) / MonoDroid:   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <4032d0be3ee64d1a892a0f3849515de6>:0 
Info (7764) / MonoDroid:   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.16(intptr,intptr,intptr)
Info (7764) / MonoDroid:   --- End of managed Java.Lang.RuntimeException stack trace ---
Info (7764) / MonoDroid: android.content.res.Resources$NotFoundException: File Gör Mapbox kartor bättre from xml type layout resource ID #0x7f0b004f
Info (7764) / MonoDroid: 	at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1243)
Info (7764) / MonoDroid: 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2172)
Info (7764) / MonoDroid: 	at android.content.res.Resources.getLayout(Resources.java:1170)
Info (7764) / MonoDroid: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
Info (7764) / MonoDroid: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
Info (7764) / MonoDroid: 	at crc64f9604ce5c917d1e0.MainActivity.n_onCreate(Native Method)
Info (7764) / MonoDroid: 	at crc64f9604ce5c917d1e0.MainActivity.onCreate(MainActivity.java:40)
Info (7764) / MonoDroid: 	at android.app.Activity.performCreate(Activity.java:7335)
Info (7764) / MonoDroid: 	at android.app.Activity.performCreate(Activity.java:7326)
Info (7764) / MonoDroid: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
Info (7764) / MonoDroid: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
Info (7764) / MonoDroid: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3284)
Info (7764) / MonoDroid: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
Info (7764) / MonoDroid: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
Info (7764) / MonoDroid: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
Info (7764) / MonoDroid: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1972)
Info (7764) / MonoDroid: 	at android.os.Handler.dispatchMessage(Handler.java:106)
Info (7764) / MonoDroid: 	at android.os.Looper.loop(Looper.java:214)
Info (7764) / MonoDroid: 	at android.app.ActivityThread.main(ActivityThread.java:7179)
Info (7764) / MonoDroid: 	at java.lang.reflect.Method.invoke(Native Method)
Info (7764) / MonoDroid: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
Info (7764) / MonoDroid: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
Info (7764) / MonoDroid: Caused by: java.io.FileNotFoundException: Gör Mapbox kartor bättre
Info (7764) / MonoDroid: 	at android.content.res.AssetManager.nativeOpenXmlAsset(Native Method)
Info (7764) / MonoDroid: 	at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:1009)
Info (7764) / MonoDroid: 	at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1227)
Info (7764) / MonoDroid: 	... 21 more
`

**Comment by mindport** [comment]
Seams to work better when adding this to my proguard.cfg 
 `-keep class com.mapbox.** { *; }`
I'll close this when verified.

**Comment by mindport** [comment]
Nope! Still there I'm afraid.
